//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOTander.Models
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    public partial class Shops
    {
        public Shops()
        {
            this.Employees = new ObservableCollection<Employees>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
